version: 0.2
phases:
  install:
    commands:
      - chmod 755 check-s3-object-version.sh
      - ./check-s3-object-version.sh    
  build:
    commands:
artifacts:
  type: zip
  files:
    - data.yaml
    - outputdata.yaml
